import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-bg px-4 md:px-6 py-12 md:py-16">
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="font-display font-bold text-xl tracking-tight block mb-10">
          feedback<span className="text-accent">loop</span>
        </Link>

        <h1 className="font-display font-bold text-3xl md:text-4xl mb-2">Terms of Service</h1>
        <p className="text-text-muted text-sm font-mono mb-10">Last updated: March 2025</p>

        <div className="prose prose-invert max-w-none space-y-8 text-text-muted leading-relaxed">

          <section>
            <h2 className="font-display font-semibold text-xl text-text-primary mb-3">1. Acceptance of terms</h2>
            <p>By creating an account or using FeedbackLoop, you agree to these Terms of Service. If you do not agree, please do not use the service.</p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-xl text-text-primary mb-3">2. What FeedbackLoop is</h2>
            <p>FeedbackLoop is an AI-powered tool that analyzes websites and code snippets for issues related to UX, performance, security, accessibility, and SEO. Results are generated by AI and are provided for informational purposes only. We do not guarantee that all issues will be detected or that suggested fixes are always correct.</p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-xl text-text-primary mb-3">3. Acceptable use</h2>
            <p>You agree to use FeedbackLoop only for lawful purposes. You must not:</p>
            <ul className="list-disc list-inside space-y-2 mt-3">
              <li>Submit URLs or code that you do not have permission to analyze</li>
              <li>Attempt to abuse, overload, or exploit the service</li>
              <li>Use the service to scan for vulnerabilities in systems you do not own</li>
              <li>Create multiple accounts to bypass plan limits</li>
              <li>Resell or redistribute the AI-generated results as your own product</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display font-semibold text-xl text-text-primary mb-3">4. Plans and billing</h2>
            <p>FeedbackLoop offers Free, Developer, and Pro plans. Paid plans are billed monthly through Lemon Squeezy. You may cancel at any time — cancellation takes effect at the end of your current billing period. We do not offer refunds for partial months.</p>
            <p className="mt-3">The early bird promotion (Pro free for 3 months) is available to the first 100 users who sign up. After 3 months, your account automatically reverts to the Free plan unless you subscribe to a paid plan.</p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-xl text-text-primary mb-3">5. Intellectual property</h2>
            <p>You retain full ownership of any code or URLs you submit. By submitting content, you grant us a limited license to process it through our AI systems solely to provide the service. We do not claim ownership of your content and do not use it to train AI models.</p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-xl text-text-primary mb-3">6. Disclaimer of warranties</h2>
            <p>FeedbackLoop is provided "as is" without warranties of any kind. AI-generated feedback may contain errors or omissions. We are not liable for any damages resulting from your use of or reliance on the service.</p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-xl text-text-primary mb-3">7. Limitation of liability</h2>
            <p>To the maximum extent permitted by law, FeedbackLoop shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability shall not exceed the amount you paid us in the 3 months prior to any claim.</p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-xl text-text-primary mb-3">8. Termination</h2>
            <p>We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time by contacting support@feedbackloop.app.</p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-xl text-text-primary mb-3">9. Changes to these terms</h2>
            <p>We may update these terms from time to time. We will notify you of significant changes via email. Continued use of FeedbackLoop after changes means you accept the updated terms.</p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-xl text-text-primary mb-3">10. Contact</h2>
            <p>For any questions about these terms, contact us at <span className="text-accent"><a href="mailto:abdullah.muhammad.xyz@gmail.com">support</a></span>.</p>
          </section>

        </div>

        <div className="mt-12 pt-8 border-t border-border flex flex-wrap gap-4 text-sm text-text-muted">
          <Link href="/" className="hover:text-text-primary transition-colors">← Home</Link>
          <Link href="/privacy" className="hover:text-text-primary transition-colors">Privacy Policy</Link>
          <Link href="/pricing" className="hover:text-text-primary transition-colors">Pricing</Link>
        </div>
      </div>
    </div>
  );
}